
export const products = [
    {
    id : "mfpm_0001" ,
    type_product : "MFP" , 
    model : "MX622adhe" ,
    mark : "Lexmark" , 
    type_model : "Monochrome Laser" , 
    type_function : "Multi Function Printer" , 
    url_img : "img/mx622adhe.png" , 
    stock : "5" , 
    price : "570" , 
    detail: "The Lexmark MX622adhe offers printing at up to 50 pages per minute*, superior print quality, enhanced security and standard hard drive.", 
    print_speed: "Print Speed Up to 50 ppm" , 
    recommended: "Recommended Monthly Page Volume: 2000 - 20000 pages"
    },
    {
    id : "mfpc_0001" ,
    type_product : "MFP" , 
    model : "CX622ade" , 
    mark : "Lexmark" , 
    type_model : "Color Laser" , 
    type_function : "Multi Function Printer" , 
    url_img : "img/cx622ade.png" , 
    stock : "12" , 
    price : "630" , 
    detail: "The multifunction Lexmark CX622ade combines colour output at as fast as 40 [38] ppm* with scanning that can reach 100 [94] images per minute for exceptional performance.", 
    print_speed: "Print Speed: Up to 38 ppm" , 
    recommended: "Recommended Monthly Page Volume: 1500 - 10000 pages"
    },
    {
    id : "prtm_0001" ,
    type_product : "PRINTER" , 
    model : "MS622de" , 
    mark : "Lexmark" , 
    type_model : "Monochrome Laser" , 
    type_function : "Printer" , 
    url_img : "img/ms622de.png" ,
    stock : "7" , 
    price : "450" ,  
    detail: "The Lexmark MS622de prints up to 47 pages per minute* and offers the versatility of e-Task, enhanced security and built-in durability.", 
    print_speed: "Print Speed: Up to 47 ppm" , 
    recommended: "Recommended Monthly Page Volume: 2000 - 20000 pages"
    },
    {
    id : "mfpm_0002" ,
    type_product : "MFP" , 
    model : "MX522adhe" ,
    mark : "Lexmark" , 
    type_model : "Monochrome Laser" , 
    type_function : "Multi Function Printer" , 
    url_img : "img/mx522adhe.png" , 
    stock : "11" , 
    price : "350" , 
    detail: "Get performance plus the durability of long-life components with the MX522adhe, the fax-equipped up-to 46 page-per-minute* multifunction product with standard hard drive.", 
    print_speed: "Print Speed Up to 46 ppm" , 
    recommended: "Recommended Monthly Page Volume: 2000 - 15000 pages"
    },
    {
    id : "mfpc_0002" ,
    type_product : "MFP" , 
    model : "CX522ade" ,
    mark : "Lexmark" , 
    type_model : "Color Laser" , 
    type_function : "Multi Function Printer" , 
    url_img : "img/cx522ade.png" , 
    stock : "15" , 
    price : "415" , 
    detail: "The multifunction Lexmark CX522ade builds on output at up to 35 pages per minute* with a 4.3-inch [10.9-cm] color touch screen.", 
    print_speed: "Print Speed Up to 35 ppm" , 
    recommended: "Recommended Monthly Page Volume: 1500 - 8500 pages"
    },
    {
    id : "mfpm_0003" ,
    type_product : "MFP" , 
    model : "MX722adhe" ,
    mark : "Lexmark" , 
    type_model : "Monochrome Laser" , 
    type_function : "Multi Function Printer" , 
    url_img : "img/mx722adhe.png" , 
    stock : "10" , 
    price : "850" , 
    detail: "Output up to 70 ppm* and a standard hard disk help the flexibly configurable, OCR-equipped Lexmark MX722adhe monochrome multifunction product meet large-workgroup needs.", 
    print_speed: "Print Speed Up to 70 ppm" , 
    recommended: "Recommended Monthly Page Volume: 5000 - 100000 pages"
    },
    {
    id : "prtm_0001" ,
    type_product : "PRINTER" , 
    model : "MS521dn" ,
    mark : "Lexmark" , 
    type_model : "Monochrome Laser" , 
    type_function : "Printer" , 
    url_img : "img/ms521dn.png" , 
    stock : "18" , 
    price : "512" , 
    detail: "With its powerful processor, 46 page-per-minute output, enhanced security and built-in durability, the MS521dn supports the success of mid-size workgroups in all their mono printing.", 
    print_speed: "Print Speed Up to 46 ppm" , 
    recommended: "Recommended Monthly Page Volume: 2000 - 15000 pages"
    },
    {
    id : "prtc_0001" ,
    type_product : "PRINTER" , 
    model : "CS521dn" ,
    mark : "Lexmark" , 
    type_model : "Color Laser" , 
    type_function : "Printer" , 
    url_img : "img/cs521dn.png" , 
    stock : "16" , 
    price : "610" , 
    detail: "The up-to-35-ppm* Lexmark CS521dn helps you control the cost of color output with high-yield replacement toner and tools that minimize toner consumption.", 
    print_speed: "Print Speed Up to 35 ppm" , 
    recommended: "Recommended Monthly Page Volume: 1500 - 8500 pages"
    },
    {
    id : "prtc_0002" ,
    type_product : "PRINTER" , 
    model : "CS720dt" ,
    mark : "Lexmark" , 
    type_model : "Color Laser" , 
    type_function : "Printer" , 
    url_img : "img/cs720dt.png" , 
    stock : "5" , 
    price : "1115" , 
    detail: "The Lexmark CS720dte offers workgroup-level printing performance in a simple, feature-rich package that’s easy to use and comes with extra input capacity.", 
    print_speed: "Print Speed Up to 40 ppm" , 
    recommended: "Recommended Monthly Page Volume: 1500 - 15000 pages"
    },
    {
    id : "prtm_0003" ,
    type_product : "PRINTER" , 
    model : "MS421dn" ,
    mark : "Lexmark" , 
    type_model : "Monochrome Laser" , 
    type_function : "Printer" , 
    url_img : "img/ms421dn.png" , 
    stock : "14" , 
    price : "275" , 
    detail: "Strike the perfect balance of performance and affordability in small-workgroup mono printing with the up-to 42-page-per-minute* Lexmark MS421dn, featuring standard two-sided printing, enhanced security and built-in durability.", 
    print_speed: "Print Speed Up to 42 ppm" , 
    recommended: "Recommended Monthly Page Volume: 1000 - 10000 pages"
    }
]